diabete/urls.py
from django.conf.urls import patterns
from django.conf.urls import url as _url
from mysite import settings
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from diabete import views
from django.core.urlresolvers import reverse
from datetime import datetime

class StaticViewSitemap(Sitemap):
    def priority(self,obj):
        if obj == 'diabete:index':
            return 1
        else:
            return 0.8

    changefreq = 'daily'

    def lastmod(self, obj):
        return datetime.now()

    def items(self):
        return ['diabete:index', 'diabete:about', 'diabete:contacts']

    def location(self, item):
        return reverse(item)

sitemaps = {
  'static': StaticViewSitemap,
}

urlpatterns = patterns('',
    _url(r'^$', views.IndexView.as_view(), name='index'),
    _url(r'^google8337acc13a0675a4.html/$', views.Google.as_view(), name='google'),
    _url(r'^0c78070968be.html/$', views.Yandex.as_view(), name='yandex'),
    _url(r'^about/$', views.about, name='about'),
    _url(r'^contacts/$', views.contacts, name='contacts'),
    _url(r'^video/$', views.video, name='video'),
    _url(r'^result/$', views.result, name='result'),
    _url(r'^diary/$', views.diary, name='diary'),
    _url(r'^edit_note/$', views.edit_note, name='edit_note'),
    _url(r'^fav_products/$', views.fav_products, name='fav_products'),
    _url(r'^adding_to_fav/$', views.adding_to_fav, name='adding_to_fav'),
    _url(r'^delete_fav/$', views.delete_fav, name='delete_fav'),
    _url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'diabete/login.html','extra_context':{'title':'Войти'}}, name='login'),
    _url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/','extra_context':{'title':'Выйти'}}, name='logout'),
    _url(r'^accounts/register/$', views.register, name='register'),
    (r'^favicon\.ico$',RedirectView.as_view(url=settings.STATIC_URL + 'diabete/favicon.ico')),
    _url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mysite import settings
from django.views.generic import RedirectView

urlpatterns = patterns('',
    #url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('diabete.urls', namespace="diabete")),
)

diabete/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    product_GI = models.CharField(max_length=4)
    product_carb = models.CharField(max_length=4)
    pub_date = models.DateTimeField('date published')

    def __str__(self):              # __unicode__ on Python 2
        return self.product_name

class Favorite_product(models.Model):
    username = models.ForeignKey(User,default='')
    product_name = models.CharField(max_length=100)
    product_GI = models.CharField(max_length=4)
    product_carb = models.CharField(max_length=4)
    pub_date = models.DateTimeField('date published')

    def __str__(self):              # __unicode__ on Python 2
        return self.product_name

class Note_diary_day(models.Model): #дневная запись
    username = models.ForeignKey(User,default='')
    name = models.CharField(max_length=10)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Note_diary(models.Model): # запись одного приема пищи
    note_diary_date = models.ForeignKey(Note_diary_day,default='')
    name = models.CharField(max_length=10) #название приема пищи
    dose = models.CharField(max_length=4)
    total_carb = models.CharField(max_length=50)
    glu_level = models.CharField(max_length=4)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Note_diary_product(models.Model): #запись одного продукта
    note_diary = models.ForeignKey(Note_diary,default='')
    product_name = models.CharField(max_length=100)
    product_GI = models.CharField(max_length=4)
    product_carb = models.CharField(max_length=4)
    product_mass = models.CharField(max_length=7)
    pub_date = models.DateTimeField('date published')

    def __str__(self):              # __unicode__ on Python 2
        return self.product_name

diabete/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ( "username", "email" )

diabete/views.py
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from diabete.forms import UserCreateForm
from django.contrib.auth import authenticate, login
import datetime
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext
from diabete.models import Product, Note_diary_day, Note_diary, Note_diary_product
from diabete.my_func import my_trans
from django import forms


class IndexView(generic.ListView):
    #model = Product
    template_name = 'diabete/index.html'
    context_object_name = 'products_for_select'

    def get_queryset(self):
        return Product.objects.order_by('product_name')

    '''@method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)'''

class Google(generic.TemplateView):
    template_name = 'diabete/google8337acc13a0675a4.html'

class Yandex(generic.TemplateView):
    template_name = 'diabete/0c78070968be.html'

def about(request):
    return render(request,'diabete/about.html')

def contacts(request):
    return render(request,'diabete/contacts.html')

def video(request):
    return render(request,'diabete/video.html')

def delete_fav(request):
    for product in request.POST:
        product_delete = request.user.favorite_product_set.filter(product_name=product)
        product_delete.delete()
    return HttpResponseRedirect(reverse('diabete:fav_products'))

def adding_to_fav(request):
    products = [] #name, GI, carb; -3: csrf, product (selected), coef
    ids=[i[len('product_name'):] for i in request.POST if i.startswith('product_name')] #id of products
    ids.sort(key=(lambda x: int(x)))
    for i in range(len(ids)):
        products.append([])
        for j in range(3):
            products[i].append('')
        products[i].append(ids[i])
    for i in request.POST:
        if i.startswith('product_name'):
            products[ids.index(i[len('product_name'):])][0]=request.POST[i].replace('\t','').replace('\n','').strip()
        if i.startswith('product_GI'):
            products[ids.index(i[len('product_GI'):])][1]=request.POST[i].replace(',','.')
        if i.startswith('product_carb'):
            products[ids.index(i[len('product_carb'):])][2]=request.POST[i].replace(',','.')
    if request.user.is_authenticated():
        for product_id in ids:
            name_of_product = products[ids.index(product_id)][0] if products[ids.index(product_id)][0] else "Имя не задано"
            if (request.user.favorite_product_set.filter(product_name=name_of_product)):
                product = request.user.favorite_product_set.filter(product_name=name_of_product)
                product.delete()

            new_product = request.user.favorite_product_set.create(product_name=name_of_product,
product_GI=products[ids.index(product_id)][1],product_carb=products[ids.index(product_id)][2],
pub_date=datetime.datetime.now())

    return HttpResponseRedirect(reverse('diabete:fav_products'))

def result(request):
    error_message_cant_calculate = ''
    error_message_diary = ''
    _total_carb=0
    products = [] #name, GI, carb, gram; -3: csrf, product (selected), coef
    ids=[i[len('product_name'):] for i in request.POST if i.startswith('product_name')] #id of products
    ids.sort(key=(lambda x: int(x)))
    for i in range(len(ids)):
        products.append([])
        for j in range(4):
            products[i].append('')
        products[i].append(ids[i])
    for i in request.POST:
        if i.startswith('product_name'):
            products[ids.index(i[len('product_name'):])][0]=request.POST[i].replace('\t','').replace('\n','').strip()
        if i.startswith('product_GI'):
            products[ids.index(i[len('product_GI'):])][1]=request.POST[i].lstrip('-').replace(',','.')
        if i.startswith('product_carb'):
            products[ids.index(i[len('product_carb'):])][2]=request.POST[i].lstrip('-').replace(',','.')
        if i.startswith('product_mass'):
            products[ids.index(i[len('product_mass'):])][3]=request.POST[i].lstrip('-').replace(',','.')
    for i in range(len(products)):
        try:
            _total_carb += float(products[i][3])*float(products[i][2])/100
        except:
            pass
    try:
        coef = request.POST['coef'].replace(',','.')
    except:
        coef = '0'
    try:
        _dose = float(coef)*_total_carb/12
    except:
        _dose = 0
        error_message_cant_calculate = 'Ошибка обработки данных. Убедитесь в корректности вводимых значений.'
    _dose = '%.2f' % _dose
    _total_carb = '%.2f' % _total_carb
    time_now = datetime.datetime.now()
    if ids:
        products_max_index = max(int(ids[-1]),Product.objects.latest('id').id)
    else:
        products_max_index = Product.objects.latest('id').id
    years = list(range(2013,time_now.year+1))
    months = ['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь']
    days = list(range(1,32))
    hours = list(range(0,24))
    minutes = list(range(0,60))
    seconds = list(range(0,60))
    if 'edit_note_diary' in request.POST:
        edit_note_diary = request.POST['edit_note_diary']
        note_diary_day_id = request.POST['note_diary_day_id']
        note_diary_id = request.POST['note_diary_id']
    else:
        edit_note_diary = ''
        note_diary_day_id = ''
        note_diary_id = ''
    if 'glu_level' in request.POST:
        glu_level = request.POST['glu_level'].replace(',','.')
        dose_by_user = request.POST['dose'].replace(',','.')
        try:
            time=datetime.datetime.strptime(request.POST['year']+'.'+request.POST['month']+'.'+request.POST['day']+'.'+request.POST['hour']+'.'+request.POST['minute']+'.'+request.POST['second'],"%Y.%m.%d.%H.%M.%S")
        except:
            if request.POST['month'] == '2':
                date_day = '28'
            else:
                date_day = '30'
            time = datetime.datetime.strptime(request.POST['year']+'.'+request.POST['month']+'.'+date_day+'.'+request.POST['hour']+'.'+request.POST['minute']+'.'+request.POST['second'],"%Y.%m.%d.%H.%M.%S")
            error_message_diary = 'Указанной Вами даты не существует. Пожалуйста, произведите расчет занаво.'
    else:
        glu_level = '0.0'
        dose_by_user = '0.0'
        time = time_now
    if 'calc' in request.POST or request.method=='GET':
        pass
    else: # записать в дневник
        utc_diff=datetime.datetime.now()-datetime.datetime.utcnow()
        format_day = '%Y.%m.%d'
        format_note_diary = '%H:%M:%S'
        if error_message_diary:
            pass
        else:
            if time>time_now:
                error_message_diary = 'Запись в дневник не может быть осуществлена на будущую дату. Пожалуйста, произведите расчет занаво.'
    if error_message_diary or 'calc' in request.POST or request.method=='GET':
        return render(request, 'diabete/result.html',{
                'products_for_select': Product.objects.order_by('product_name'),
                'coef':coef,
                'products':products,
                'dose': _dose,
                'dose_by_user':dose_by_user,
                'total_carb': _total_carb,
                'glu_level': glu_level,
                'products_max_index': products_max_index,
                'error_message_cant_calculate': error_message_cant_calculate,
                'error_message_diary':error_message_diary,
                'time':time,
                'years':years,
                'months':months,
                'days':days,
                'hours':hours,
                'minutes':minutes,
                'seconds':seconds,
                'edit_note_diary':edit_note_diary,
                'note_diary_day_id':note_diary_day_id,
                'note_diary_id':note_diary_id,
            })
    else:
        if ((request.user.note_diary_day_set.count()==0 or (not request.user.note_diary_day_set.filter(name=time.strftime(format_day))))): #request.user.note_diary_day_set.last().pub_date+utc_diff
            current_note_diary_day = request.user.note_diary_day_set.create(name=time.strftime(format_day),pub_date=time)
        else:
            current_note_diary_day = request.user.note_diary_day_set.filter(name=time.strftime(format_day))[0]

        current_note_diary = current_note_diary_day.note_diary_set.create(name=time.strftime(format_note_diary),dose=request.POST['dose'].replace(',','.'),total_carb=_total_carb,pub_date=time,glu_level=request.POST['glu_level'].replace(',','.'))
        for product_id in ids:
            try:
                note_product = current_note_diary.note_diary_product_set.create(product_name=products[ids.index(product_id)][0],
product_GI=products[ids.index(product_id)][1],product_carb=products[ids.index(product_id)][2],product_mass=products[ids.index(product_id)][3],
pub_date=time)
            except:
                pass
        if note_diary_id:
            try:
                request.user.note_diary_day_set.get(id=note_diary_day_id).note_diary_set.get(id=note_diary_id).delete()
            except:
                pass
        return HttpResponseRedirect("%s?date=%i_%i_%i" % (reverse('diabete:diary'),time.year,time.month-1,time.day))

def fav_products(request):
    if not request.user.is_authenticated():
        return  HttpResponseRedirect(reverse('diabete:index'))
    products_for_select = Product.objects.order_by('product_name')
    users_fav_products = request.user.favorite_product_set.order_by('product_name')
    return render(request, 'diabete/fav_products.html',{
        'products_for_select':products_for_select,
        'users_fav_products':users_fav_products,
    })

def diary(request):
    if not request.user.is_authenticated():

diabete/templates/diabete/0c78070968be.html
838345bb772e

diabete/templates/diabete/base.html
{% load staticfiles %}{% load diabete_extras %}<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		{% block description %}{% endblock %}
		<link rel="shortcut icon" href="{% static 'diabete/favicon.ico' %}" type="image/x-icon">
		<link type="text/css" rel="stylesheet" href="{% static 'diabete/stylesheet.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'diabete/chosen.css' %}"/>
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		<div class="header">
			<h3 style="float:right;margin-top:0px">
			{% if user.is_authenticated %}Добро пожаловать, {{ user.username }}.{% else %}Добро пожаловать на tvoy-diabete.ru{% endif %}	
			</h3>
			<div class="container" style="clear:both">
				<ul class="menu-right">
					{% if user.is_authenticated %}
						<li><a href="{% url 'diabete:logout' %}">Выйти</a></li>
					{% else %}
						<li><a href="{% url 'diabete:register' %}">Регистрация</a></li>
						<li><a href="{% url 'diabete:login' %}?next=/">Войти</a></li>
					{% endif %}				
				</ul>
				<ul class="menu-left">
					<li><a href="{% url 'diabete:index' %}">Главная</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'diabete:fav_products' %}">Любимые продукты</a></li>
					<li><a href="{% url 'diabete:diary' %}?date=today">Дневник</a></li>
					{% endif %}
					<li><a href="{% url 'diabete:video' %}">Обучающее видео</a></li>				
				</ul>
			</div>
		</div>
		<div id="main">
			{% block slides %}{% endblock %}
		</div>
		<div id="footer">
			<ul class="menu-left">
				<li><a href="{% url 'diabete:about' %}">О сайте</a></li>
				<li><a href="{% url 'diabete:contacts' %}">Контакты</a></li>
			</ul>
		</div>
		{% block max_index %}{% endblock %}
		<script src="{% static 'diabete/jquery.min.js' %}"></script>
		<script src="{% static 'diabete/diabete.js' %}"></script>
		
		<script src="{% static 'diabete/chosen.jquery.min.js' %}"></script>
		<script type="text/javascript">
			$('.chosen-select').chosen();
		</script>
		<!--<script src="http://ie.microsoft.com/testdrive/HTML5/CompatInspector/inspector.js"></script>-->
		<script type="text/javascript">
<!--
function cloneAndCopy(nodeId, tonodeId, deep)
{
var toClone = document.getElementById(nodeId);
var clonedNode = toClone.cloneNode(deep);
var insertPoint = document.getElementById(tonodeId);
insertPoint.appendChild(clonedNode);
}
//cloneAndCopy('product-select-calc','product-select-fav',true);
//-->
	</script>
	</body>
</html>

diabete/templates/diabete/contacts.html
{% extends "diabete/base.html" %}{% load staticfiles %}

{% block title %}Контакты{% endblock %}
{% block description %}
<meta name="keywords" content="Бабинцев, Алексей, разработчик, контакт, диабет, support, tvoy-diabete">
<meta name="description" content="Контакты сайта tvoy-diabete.ru">
{% endblock %}	

{% block slides %}
<div class="slide usual-slide active-slide">
	<h2 style="margin:5px 0px 5px 0px">Контакты</h2>
	<p style="font-size:20; margin-top: 5px"><img src="{% static 'diabete/contacts.jpg' %}" alt="Диабет" class="leftimg">
Разработчик ресурса: Бабинцев Алексей
<p style="font-size:20">e-mail: admin@tvoy-diabete.ru</p>
<p style="font-size:20">Буду рад любым вашим отзывам, пожелания и предложениям.

</div>
{% endblock %}

	

diabete/templates/diabete/diary.html
{% extends "diabete/base.html" %}
{% load i18n %}{% load diabete_extras %}

{% block title %}Дневник{% endblock %}

{% block slides %}
<div id="hiddencontent" year="{{year}}" month="{{month}}" day="{{day}}"></div>
<div class="slide usual-slide active-slide">

<table id="calendar2">
  <thead>
    <tr><td>‹<td colspan="5"><td>›
    <tr><td>Пн<td>Вт<td>Ср<td>Чт<td>Пт<td>Сб<td>Вс
  <tbody>
</table>

<h1 style="text-align: center; margin-top: 0px; margin-bottom: 20px;float:right;width: 78%;">{% trans note_date %}</h1>
<div id="diary-note">
	
	{% if current_note_diary_day == None %}
		<h2 style="text-align: center; margin-top: 15px">На указанную дату нет ни одной записи.</h2>
	{% elif current_note_diary_day.note_diary_set.all.count == 0 %}
		<h2 style="text-align: center; margin-top: 15px">На указанную дату нет ни одной записи.</h2>
	{% else %}
		{% for note in current_note_diary_day.note_diary_set.all|dictsort:"name" %}
			<div class="table-container">
				<table>
					<thead>
						<th width=420 colspan="4">Время записи: {{note.name}}</th>
					</thead>
					<tbody>
						{% if note.note_diary_product_set.all.count > 0 %}
						<tr>
							<td width=200><span class="fat">Продукт</span></td>
							<td width=50><span class="fat">ГИ</span></td>
							<td width=80><span class="fat">Углеводы</span></td>
							<td width=80><span class="fat">Масса</span></td>
						</tr>
						{% endif %}
						{% for product in note.note_diary_product_set.all %}
							<tr>
								<td>{{ product.product_name }}</td>
								<td>{{ product.product_GI }}</td>
								<td>{{ product.product_carb }}</td>
								<td>{{ product.product_mass }}</td>
							</tr>							
						{% endfor %}
						<tr>
							<td colspan="2" class="green-cell"><B>Всего углеводов: {{note.total_carb}} г</B></td>
							<td colspan="2" class="green-cell"><B>Инсулин: {{note.dose}} ед.</B></td>
						</tr>
						<tr>
							<td colspan="4" class="red-cell"><B>Уровень сахара: {{note.glu_level}} ммоль/л</B></td>
						</tr>
					</tbody>
				</table>
				<form id="edit_note{{note.id}}" method="post" action="{% url 'diabete:edit_note' %}">
				{% csrf_token %}
				<input type=hidden value="{{note.id}}" name="note_id">
				<input type=hidden value="{{current_note_diary_day.id}}" name="note_diary_day_id">
				<div style="position:relative">
				
					<p style="margin-top:2px">
						<button class="btn_del_note" type="button">Удалить</button>
						<input class="pointer" type=Submit name="btn_edit_note" value="Редактировать" form="edit_note{{note.id}}">
						<input class="pointer" type=Submit name="btn_template" value="Использовать как шаблон" form="edit_note{{note.id}}">
					</p>
					<div class="yes_no_window">
						<p style="margin:0px 2px 10px 2px ;">Вы уверены, что хотите удалить запись?</p>
						<p style="margin:0px 2px 5px 80px">
							<input class="pointer" type=Submit name="btn_delete_note" value="Да" form="edit_note{{note.id}}">
							<button class="no_window" type="button" style="margin-left:40px">Нет</button>
						</p>
					</div>
				
				</div>
				</form>
			</div>
		{% endfor %}
	{% endif %}
	
</div>

</div>
{% endblock %}

diabete/templates/diabete/fav_products.html
{% extends "diabete/base.html" %}

{% block title %}Любимые продукты{% endblock %}

{% block max_index %}
	<div id="hiddencontent" products_num={{products_for_select.all.count}}></div>
	<div id="num_users_fav_products" products_num={{users_fav_products.all.count}}></div>
{% endblock %}

{% block slides %}
{% if user.is_authenticated %}
<div class="slide usual-slide active-slide">
	<div class="selector" id="product-select-calc">
		<select data-placeholder="Выберете продукт" style="width:400px;" id="product" name=product class="chosen-select">
			<option value=""></option>
				{% for product in products_for_select.all %}			
					<option id="{{ product.id }}" GI="{{ product.product_GI }}" carb="{{ product.product_carb }}" value="{{ forloop.counter0 }}">{{ product.product_name }}		
				{% endfor %}
		</select>
	</div>
	<div class="selector">
		<a href="#" class="adding_to_fav"><button type="button">Добавить к любимым продуктам</button></a>
	</div>
	<div class="left-table" style="height: 90%">
		<div class="table-container">
			<form id="chosen-fav-products" method="post" action="{% url 'diabete:adding_to_fav' %}">
			{% csrf_token %}
				<table class="table" id="table-chosen-fav-products">
					<thead>
						<th colspan="3">Новые любимые продукты</th>
					</thead>
					<tbody>
						<tr>
							<td width=200><span class="fat">Продукт</span></td>
							<td width=50><span class="fat">ГИ</span></td>
							<td width=80><span class="fat">Углеводы</span></td>							
						</tr>
					</tbody>
				</table>
				<p><input class="pointer" type=Submit value="Подтвердить"  form="chosen-fav-products">
				<a href="#" class="adding_new_to_fav"><button type="button">Создать новый продукт</button></a>
			</form>
		</div>
	</div>
	<div class="right-table" style="height: 90%; width: 52%">
		<div class="table-container">
			<form id="users-fav-products" method="post" action="{% url 'diabete:delete_fav' %}">
			{% csrf_token %}
				<table class="table" id="table-users-fav-products">
					<thead>
						<th colspan="4">Любимые продукты</th>
					</thead>
					<tbody>
						<tr>
							<td width=200><span class="fat">Продукт</span></td>
							<td width=50><span class="fat">ГИ</span></td>
							<td width=80><span class="fat">Углеводы</span></td>		
							<td width=80><span class="fat"><a class="select-all" href="#">Выбрать</a></span></td>
						</tr>
						{% for product in users_fav_products.all %}
							<tr>
								<td id="product_name{{ forloop.counter0 }}">{{ product.product_name }}</td>
								<td id="product_GI{{ forloop.counter0 }}">{{ product.product_GI }}</td>
								<td id="product_carb{{ forloop.counter0 }}">{{ product.product_carb }}</td>
								<td><input id="check{{ forloop.counter0 }}" type="checkbox" name="{{ product.product_name }}"/></td>
							</tr>							
						{% endfor %}
					</tbody>
				</table>
				<p><input class="pointer" type=Submit value="Удалить выбранное"  form="users-fav-products">
				<a href="#" class="edit_fav_products"><button type="button">Редактировать выбранное</button></a>
			</form>
		</div>
	</div>
</div>
{% else %}
<h2>Только зарегистрированные пользователи могут заходить на эту страницу.</h2>
{% endif %}
{% endblock %}

diabete/templates/diabete/google8337acc13a0675a4.html
google-site-verification: google8337acc13a0675a4.html

diabete/templates/diabete/login.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block content_title %}{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'diabete:index' %}">На главную</a>
</div>
{% endblock %}

{% block content %}
{% if form.errors %}
<p>Неправильные имя пользователя или пароль.</p>
{% endif %}

<div id="content-main">
<form action="{% url 'diabete:login' %}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    <label for="id_username" class="required">{{ form.username.label_tag }}:</label> {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    <label for="id_password" class="required">{{ form.password.label_tag }}</label> {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

diabete/templates/diabete/register.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block content_title %}{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'diabete:index' %}">На главную</a>
</div>
{% endblock %}

{% block content %}
{% if form.errors %}
<p>Ошибка регистрации.</p>
{% endif %}

<div id="content-main">
<form action="{% url 'diabete:register' %}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    <label for="id_username" class="required">{{ form.username.label_tag }}</label> <p>{{ form.username }}</p>
  </div>
  <div class="form-row">
  {{ form.email.errors }}
    <label for="id_email" class="required">{{ form.email.label_tag }}</label> <p>{{ form.email }}</p>
  </div>
  <div class="form-row">
    {{ form.password1.errors }}
    <label for="id_password1" class="required">{{ form.password1.label_tag }}</label> <p>{{ form.password1 }}</p>
  </div>
  <div class="form-row">
    {{ form.password2.errors }}
    <label for="id_password2" class="required">{{ form.password2.label_tag }}</label> <p>{{ form.password2 }}</p>
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Регистрация" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}